name: vscode CI

on:
  push:
    branches:
      - master
      - dev
    pull_request:
      - master
      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          #- windows-latest
        node-version:
          - 19

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & echo "Starting Xvfb..."
        shell: bash
        if: ${{ success() && matrix.os == 'ubuntu-latest' }}
      - run: npm ci
      - run: npm run lint
      - run: npm run test
        env:
          DISPLAY: ':99.0'

